#pragma once
#include <Event.h>
#include <InputEvent.h>
enum GameEventType
{
	QUIT_GAME_EVENT = NUM_INPUT_EVENT_TYPES,
	CHANGE_ANIMATION_EVENT,
	PAUSE_ANIMATION_EVENT,
	UNIT_CHANGE_EVENT,
	PLAY_SOUND_EVENT,
	CHANGE_POINT_EVENT,
	PAUSE_GAME_EVENT,
	GAME_OVER_EVENT,
	RESTART_GAME_EVENT,
	PLAYER_DIRECTION_EVENT,
	BOSS_HEALTH_EVENT,
	PLAYER_HEALTH_EVENT,
	DIFFICULTY_CHANGE_EVENT,
	SWITCH_MENUE_EVENT,
	CHANGE_LANGUAGE_EVENT,
	LOAD_FROM_SAVE_EVENT, 
	MUTE_SOUND_EVENT
};
class GameEvent : public Event
{
public:
	GameEvent(const GameEventType& type);
};

